# Generated by Django 4.2.6 on 2024-03-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_is_complete_taskmodel_is_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='taskTitle',
            field=models.CharField(max_length=200),
        ),
    ]
